# Generated by Django 5.1.6 on 2025-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
